# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./volumes/data/backup_db:/backup_db
      - ./volumes/data/postgres/data:/var/lib/postgresql/data
      - ./volumes/data/postgres/config:/etc/postgresql
      - ./volumes/data/postgres/logs:/var/log/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PORT_DB_HOST}:${PORT_DB_CONTAINER}"
    networks:
      - postgres-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file: ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PORT_PG_HOST}:${PORT_PG_CONTAINER}"
    networks:
      - postgres-network
    depends_on:
      - db
  
networks: 
  postgres-network: